### ISSUE TITLE
ingress-nginx-3.9.0.tgz does not exist in CP7.0

### ISSUE THREAD

**Issue by andylwelch** [HCL-TECH-SOFTWARE/connections-automation#104]
Deploying CP7.0 fails because file download task fails as it does not exist in the extracted CP7.0 zip

![image](https://user-images.githubusercontent.com/7505965/114795888-01df3e00-9dd3-11eb-9e6e-5fbf73573934.png)

For any others who encounter this issue, perhaps try the following URL:
https://github.com/kubernetes/ingress-nginx/releases/download/ingress-nginx-3.9.0/ingress-nginx-3.9.0.tgz

**Comment by dejo1307** [comment]
Hi Andy,

Thanks a lot, will be fixed in the next push. 

Really appreciated,
Dejan

**Comment by ukhare** [comment]
@andylwelch I believe this was ractified too ?
Could you please check and confirm ?
