### ISSUE TITLE
Login with Chrome not possible

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#114]
All chromebased browsers do not allow login. I found this line in `httpd.conf` as reason:

`# Teams SameSite Fix`
`Header edit Set-Cookie ^(.*)$ "$1; SameSite=None"`

If I comment this out, the login works without problems. Chrome rejects cookies with Samesite=None since version 80 by default! https://www.chromestatus.com/feature/5633521622188032

**Comment by dejo1307** [comment]
Hey Christoph,

Thanks a lot, already talking to people about this. It was added back in September as a requirement at that time for Teams integration, but let me see if it can be removed (I guess it should at least).

**Comment by dejo1307** [comment]
Fix is part of https://github.com/HCL-TECH-SOFTWARE/connections-automation/releases/tag/0.4.1. 

The config was introduced during RnD of CNX 7 in September, and is worked around during one of the steps in post install playbook, but commenting it out will definitely make it less confusing for everyone. 

Thanks a lot for pointing this out.
