### ISSUE TITLE
Connections 7 iFix installation

### ISSUE THREAD

**Issue by Praveenk89** [HCL-TECH-SOFTWARE/connections-automation#137]
Hello,

We successfully installed HCL Connections 7.0 using Ansible on a RHEL machine, but when we try to install Connections iFix using Ansible, the process gets stuck at the following stage. I've waited at least an hour, but the installation process is still stalled. We also checked the Connections logs, but only the Connections cluster stopped showing up in the logs, and nothing else was getting into the logs file.

TASK [ifix : Create a new updateInstaller directory] *******************************************************************************************************************
changed: [devapps.test.com] => (item=/opt/HCL/Connections/updateInstaller/fixes)
ok: [devapps.test.com] => (item=/opt/IBM/Binaries/cnx-ifix/)

TASK [ifix : Download the updateInstaller from http://devapps.test.com:8001/Connections7/updateInstaller_2102.zip] **************************************************
changed: [devapps.test.com]

TASK [ifix : Extract the updateInstaller] ******************************************************************************************************************************
changed: [devapps.test.com]

TASK [ifix : Add +x to updateInstaller] ********************************************************************************************************************************
changed: [devapps.test.com]

TASK [ifix : Download the iFixes HCL_Connections_70_Update.jar] ********************************************************************************************************
changed: [devapps.test.com]

TASK [ifix : Install Connections iFix] *********************************************************************************************************************************
included: /opt/HCL/connections_ansible/connections-automation-main/roles/hcl/connections/ifix/tasks/setup_ifix.yml for devapps.test.com

TASK [ifix : Verify if iFix LO100079 is already installed] *************************************************************************************************************
ok: [devapps.test.com]

TASK [ifix : Run the iFix install for LO100079] ************************************************************************************************************************

Thanks
PK

**Comment by nitinjagjivan** [comment]
Hi PK,
I tried installing Connections iFix using Ansible on CentOS7 and it installed successfully. It took around 25 minutes at **TASK [ifix : Run the iFix install for CFix.70.2106]** and moved to the next step:

_TASK [ifix : Add +x to updateInstaller] ***************************************************************************
changed: [devapps.test.com]

TASK [ifix : Download the iFixes CFix.70.2106-IC7.0.0.0-Common-Fix.jar] *******************************************
changed: [devapps.test.com]

TASK [ifix : Install Connections iFix] ****************************************************************************
included: ....../roles/hcl/connections/ifix/tasks/setup_ifix.yml for devapps.test.com

TASK [ifix : Verify if iFix CFix.70.2106 is already installed] ****************************************************
ok: [devapps.test.com]

TASK [ifix : Run the iFix install for CFix.70.2106] ***************************************************************
changed: [devapps.test.com]

TASK [ifix : Check updateInstaller stdout for success message] ****************************************************
ok: [devapps.test.com] => {
    "failed_when_result": false,
    "ifix_install_performed.stdout_lines": [
        "Start of [ ./updateSilent.sh ]",
        "Build 20210424_1321",
       .
       .
       .
       .
       .


Ansible code looks fine. So can you please try running it manually : 
login as root user on your devapps.test.com

and run below commands - 

cd < connections-installation-dir > /updateInstaller/HCL_Connections_Install/tools/updateInstaller 

export WAS_HOME=<WebSphere/AppServer> path e.g. /opt/IBM/WebSphere/AppServer

./updateSilent.sh -installDir <connections-installation-dir> -fix -fixDir <connections-installation-dir>/updateInstaller/fixes -install -fixes CFix.70.2106 -wasUserId <wasUserId> -wasPassword <wasPassword> -featureCustomizationBackedUp yes 

and check if it finishes all steps successfully.

**Comment by stoeps13** [comment]
Hi,
the question points to 

`ifix_apar:                                       LO100079`

which is superseeded. Since this week you can install CFix.70.2108 and for CP there is another fixpack available. 

The example variables still point to the old fix name. It would be great if HCL can create an example variables file with the latest fixes and filenames. Just the absolute minimum to get Connections up and running.

Regards
Christoph

**Comment by nitinjagjivan** [comment]
Today I tried installing LO100079 and it took around an hour to finish. Can you please try installing the latest CFix? LO100079 does not have all ears updated while CFix has. Since what's already in LO100079 is already in CFix hence the name, cumulative fixes. Going forward we can use CFixes.

**Comment by nitinjagjivan** [comment]
Hi @Praveenk89 
Can you please close this issue or please let us know if you are still facing any issues on this.
