### ISSUE TITLE
Upgrade TDI jre error

### ISSUE THREAD

**Issue by Praveenk89** [HCL-TECH-SOFTWARE/connections-automation#138]
Hello,

I'm trying to upgrade the TDI 7.2 jre using Ansible on RHEL machine but getting the following error on the screen.

failed: [devapps.test.com] (item=ojdbc8.jar) => {"ansible_loop_var": "item", "changed": false, "checksum_dest": null, "checksum_src": "967c0b1a2d5b1435324de34a9b8018d294f8f47b", "dest": "/opt/IBM/TDI/V7.20/jvm/jre/lib/ext", "elapsed": 0, "item": "ojdbc8.jar", "msg": "Destination /opt/IBM/TDI/V7.20/jvm/jre/lib does not exist", "src": "/home/citc_user/.ansible/tmp/ansible-tmp-1630498961.711784-258971-248242497747704/tmpw0bwbny5", "url": "http://devapps.test.com:8001/Oracle/ojdbc8.jar"}

Please us to resolve this issue.

Thanks
PK

**Comment by ukhare** [comment]
@Praveenk89 Could you please confirm that "devapps.test.com" is the DB server on which existing TDI is installed ?

If yes then to crosscheck if TDI is properly installed on this server then paths "opt/IBM/TDI/V7.20" and "/opt/IBM/TDI/V7.20/jvm/jre/lib/ext" should exist on the respective VM where TDI is installed.

**Comment by ukhare** [comment]
@Praveenk89 could you please confirm if your issue was fixed ?
Kindly close this issue or let us know if you are still getting same error.
