### ISSUE TITLE
HCL Docs installation error

### ISSUE THREAD

**Issue by Praveenk89** [HCL-TECH-SOFTWARE/connections-automation#140]
Hello,

I'm attempting to install HCL Docs on a Linux machine using an Ansible script, but I'm getting the following error message.

TASK [setup-environment : Mount "{{ __docs_editor_files_dest }}" "to" "{{ __docs_data_local_path }}"] ******************************************************************
fatal: [devapps.test.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ __nfsMasterAddress }}:{{ __docs_data_remote_path }}: {{ nfsMasterAddress | default( __firstNfsNode ) }}: {{ hostvars[groups['nfs_servers'][0]]['ansible_default_ipv4']['address'] }}: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_default_ipv4'\n\nThe error appears to be in '/opt/HCL/connections_ansible/connections-automation-main/roles/hcl/docs/setup-environment/tasks/mount_docs_nfs_shares.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name:                      Mount \"{{ __docs_editor_files_dest }}\" \"to\" \"{{ __docs_data_local_path }}\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

PLAY RECAP *************************************************************************************************************************************************************
devapps.test.com        : ok=18   changed=3    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

Please help us to resolve this issue.

Thanks
PK

**Comment by stoeps13** [comment]
It seems to break here: https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/9780d52b7c88766d953e098f6def7388eb7d7372/roles/hcl/docs/setup-environment/tasks/mount_docs_nfs_shares.yml#L18

As the first two tasks in that file should create the NFS share folder, it already had a problem there. Run the task manually and check what happens.

**Comment by sabrina-yee** [comment]
Hi @Praveenk89, the repo has been updated with a fix.  Please let me know if it addresses the issue you observed.  Thanks.

**Comment by nitinjagjivan** [comment]
Thanks @sabrina-yee. 

Hi @Praveenk89, 
Can you please close this issue if above fix addresses the issue you observed.
