### ISSUE TITLE
Awkward description / naming of Tasks

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#144]
The setup-connections-wizards role has some misleading names of tasks, so

https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/497ef1d1c9dfebbf3c96b280d42d00118846e756/roles/hcl/connections-wizards/tasks/setup_connections_wizards.yml#L91 and https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/497ef1d1c9dfebbf3c96b280d42d00118846e756/roles/hcl/connections-wizards/tasks/setup_connections_wizards.yml#L61
are named "cleanup" -> these tasks drop the database, yes that's cleanup too, but dropping means deleting and not cleaning.

Run migrations for everything but ICEC https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/497ef1d1c9dfebbf3c96b280d42d00118846e756/roles/hcl/connections-wizards/tasks/setup_connections_wizards.yml#L146

There are several tasks mentioning migration, but they just create the database. Migration would be 6.5 -> 7.0 but not createDB or appGrants. 

As I haven't dig into every role, I didn't create a PR for this, but consider a renaming in future versions please.

There are more and more inexperienced users of Ansible and Connections setup, so this can cause major problems when databases are dropped. Mainly because the example variables which are provided have all variables set for database "cleanup".

Regards
Christoph

**Comment by nitinjagjivan** [comment]
Noted. Thanks for the observations. It will be fixed in the next push.

**Comment by stoeps13** [comment]
Mostly fixed
