### ISSUE TITLE
Install Kubernetes playbook failing

### ISSUE THREAD

**Issue by arnaldovale** [HCL-TECH-SOFTWARE/connections-automation#152]
When trying to execute the "Install Kubernetes" Playbook, it fails in the task "Setup-master-node" with the error: 

ASK [setup-master-node : Initialize master for single node installation] ***************************************************************************************************
fatal: [cpack-server.internal.cloudapp.net]: FAILED! => {"changed": true, "cmd": ["kubeadm", "init", "--config=/tmp/k8s_ansible/kubeadm-config.yaml"], "delta": "0:00:00.675252", "end": "2021-10-27 14:29:16.222511", "msg": "non-zero return code", "rc": 1, "start": "2021-10-27 14:29:15.547259", "stderr": "W1027 14:29:15.743253    4310 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Port-6443]: Port 6443 is in use\n\t[ERROR Port-10259]: Port 10259 is in use\n\t[ERROR Port-10257]: Port 10257 is in use\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists\n\t[ERROR Port-10250]: Port 10250 is in use\n\t[ERROR Port-2379]: Port 2379 is in use\n\t[ERROR Port-2380]: Port 2380 is in use\n\t[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["W1027 14:29:15.743253    4310 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]", "error execution phase preflight: [preflight] Some fatal errors occurred:", "\t[ERROR Port-6443]: Port 6443 is in use", "\t[ERROR Port-10259]: Port 10259 is in use", "\t[ERROR Port-10257]: Port 10257 is in use", "\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists", "\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists", "\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists", "\t[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists", "\t[ERROR Port-10250]: Port 10250 is in use", "\t[ERROR Port-2379]: Port 2379 is in use", "\t[ERROR Port-2380]: Port 2380 is in use", "\t[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "[init] Using Kubernetes version: v1.19.11\n[preflight] Running pre-flight checks", "stdout_lines": ["[init] Using Kubernetes version: v1.19.11", "[preflight] Running pre-flight checks"]}

the full script output is attached. 
Appreciate your help.
[ansible_issue.txt](https://github.com/HCL-TECH-SOFTWARE/connections-automation/files/7428886/ansible_issue.txt)

**Comment by gyanenduprakash** [comment]
Can you please provide below details 
-  Ansible version
- OS details 
- K8s version (assuming 1.19.x)
I think you are trying to re install  kubeadm , so port is showing in used as per logs like as below 
**[ERROR Port-2379]: Port 2379 is in use**
Please try to reset kubeadm (Command - kubeadm reset) !!

**Comment by stoeps13** [comment]
You can add `force_destroy_kubernetes: true` into your group_vars/all.yml file, this will reinstall kubernetes if it is already deployed.

**Comment by arnaldovale** [comment]
Hi @stoeps13 . I'll try that, but this has also failed since kubernetes wasn't installed. I'll post the results here. Thanks!

**Comment by arnaldovale** [comment]
Well, its have been tried to reset kubernet and also added the force_destroy_kubernetes parameter. 
here's the output for kubeadm reset
![image](https://user-images.githubusercontent.com/67335382/141160151-134aa573-35dc-4928-a3ef-633f5a1acff0.png)

after that, when trying to run the script again, we got this output message:
TASK [taint-all-nodes : Allow pods to run on master in case of single node install] *****************************************************************************************
included: /home/operador/connections-automation/roles/third_party/kubernetes/taint-all-nodes/tasks/taint_single_node.yml for cpack-server.internal.cloudapp.net

TASK [taint-all-nodes : [Single Node] Allow pods to run on master] **********************************************************************************************************
changed: [cpack-server.internal.cloudapp.net]

TASK [taint-all-nodes : [Single Node] Label worker nodes as infrastructure for single node environment] *********************************************************************
fatal: [cpack-server.internal.cloudapp.net]: FAILED! => {"changed": true, "cmd": ["kubectl", "label", "nodes", "cpack-server.internal.cloudapp.net", "type=infrastructure", "--overwrite"], "delta": "0:00:00.113107", "end": "2021-11-10 10:38:58.655617", "msg": "non-zero return code", "rc": 1, "start": "2021-11-10 10:38:58.542510", "stderr": "Error from server (NotFound): nodes \"cpack-server.internal.cloudapp.net\" not found", "stderr_lines": ["Error from server (NotFound): nodes \"cpack-server.internal.cloudapp.net\" not found"], "stdout": "", "stdout_lines": []}

PLAY RECAP ******************************************************************************************************************************************************************
cpack-server.internal.cloudapp.net : ok=42   changed=11   unreachable=0    failed=1    skipped=22   rescued=0    ignored=3

then, if tried again:
TASK [setup-master-node : Initialize master for single node installation] ***************************************************************************************************
fatal: [cpack-server.internal.cloudapp.net]: FAILED! => {"changed": true, "cmd": ["kubeadm", "init", "--config=/tmp/k8s_ansible/kubeadm-config.yaml"], "delta": "0:00:00.712987", "end": "2021-11-10 10:53:55.580641", "msg": "non-zero return code", "rc": 1, "start": "2021-11-10 10:53:54.867654", "stderr": "W1110 10:53:55.054260    2433 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Port-6443]: Port 6443 is in use\n\t[ERROR Port-10259]: Port 10259 is in use\n\t[ERROR Port-10257]: Port 10257 is in use\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists\n\t[ERROR Port-10250]: Port 10250 is in use\n\t[ERROR Port-2379]: Port 2379 is in use\n\t[ERROR Port-2380]: Port 2380 is in use\n\t[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["W1110 10:53:55.054260    2433 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]", "error execution phase preflight: [preflight] Some fatal errors occurred:", "\t[ERROR Port-6443]: Port 6443 is in use", "\t[ERROR Port-10259]: Port 10259 is in use", "\t[ERROR Port-10257]: Port 10257 is in use", "\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists", "\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists", "\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists", "\t[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists", "\t[ERROR Port-10250]: Port 10250 is in use", "\t[ERROR Port-2379]: Port 2379 is in use", "\t[ERROR Port-2380]: Port 2380 is in use", "\t[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "[init] Using Kubernetes version: v1.19.11\n[preflight] Running pre-flight checks", "stdout_lines": ["[init] Using Kubernetes version: v1.19.11", "[preflight] Running pre-flight checks"]}

by the way, we're using ansible 2.9.2.5, OS: CentOS 7.9.2009 
and kubernetes as below:
![image](https://user-images.githubusercontent.com/67335382/141160779-73047cbd-026d-47e6-a069-e889d9386c8d.png)

**Comment by sabrina-yee** [comment]
At this point I'd suggest to start installing K8s from scratch by running this playbook first to cleanup first (please backup any data if it must be preserved) `playbooks/hcl/cleanup/cleanup-k8s.yml --tags k8s_cleanup`
After that, run `third_party/kubernetes/setup-kubernetes.yml` again.

**Comment by arnaldovale** [comment]
Hello,

I ran:

ansible-playbook -i environments/examples/cnx7/quick_start/inventory.ini playbooks/hcl/cleanup/cleanup-k8s.yml --tags k8s_cleanup

After this i got:

PLAY [Cleanup Kubernetes] ***************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [cpack-server.internal.cloudapp.net]

TASK [cleanup : Reset Kubernetes] *******************************************************************************************************************************************
changed: [cpack-server.internal.cloudapp.net]

TASK [cleanup : Cleanup K8S] ************************************************************************************************************************************************
[WARNING]: Consider using the yum module rather than running 'yum'.  If you need to use command because yum is insufficient you can add 'warn: false' to this command task
or set 'command_warnings=False' in ansible.cfg to get rid of this message.
changed: [cpack-server.internal.cloudapp.net]

TASK [cleanup : Find kubectl] ***********************************************************************************************************************************************
changed: [cpack-server.internal.cloudapp.net]

TASK [cleanup : Delete kubectl if exists] ***********************************************************************************************************************************
ok: [cpack-server.internal.cloudapp.net]

TASK [cleanup : Cleanup folders] ********************************************************************************************************************************************
changed: [cpack-server.internal.cloudapp.net] => (item=/tmp/k8s_ansible)
ok: [cpack-server.internal.cloudapp.net] => (item=/opt/helm)
ok: [cpack-server.internal.cloudapp.net] => (item=/root/.kube)
changed: [cpack-server.internal.cloudapp.net] => (item=/etc/docker/registry)
changed: [cpack-server.internal.cloudapp.net] => (item=/etc/kubernetes)
changed: [cpack-server.internal.cloudapp.net] => (item=/var/lib/etcd)

PLAY RECAP ******************************************************************************************************************************************************************
cnx-server.internal.cloudapp.net : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
cpack-server.internal.cloudapp.net : ok=7    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


I ran again:

ansible-playbook -i environments/examples/cnx7/quick_start/inventory.ini playbooks/third_party/kubernetes/setup-kubernetes.yml

I got at the end:


TASK [taint-all-nodes : [Single Node] Allow pods to run on master] **********************************************************************************************************
changed: [cpack-server.internal.cloudapp.net]

TASK [taint-all-nodes : [Single Node] Label worker nodes as infrastructure for single node environment] *********************************************************************
fatal: [cpack-server.internal.cloudapp.net]: FAILED! => {"changed": true, "cmd": ["kubectl", "label", "nodes", "cpack-server.internal.cloudapp.net", "type=infrastructure", "--overwrite"], "delta": "0:00:00.107848", "end": "2021-11-10 16:52:50.453578", "msg": "non-zero return code", "rc": 1, "start": "2021-11-10 16:52:50.345730", "stderr": "Error from server (NotFound): nodes \"cpack-server.internal.cloudapp.net\" not found", "stderr_lines": ["Error from server (NotFound): nodes \"cpack-server.internal.cloudapp.net\" not found"], "stdout": "", "stdout_lines": []}

PLAY RECAP ******************************************************************************************************************************************************************
cpack-server.internal.cloudapp.net : ok=42   changed=16   unreachable=0    failed=1    skipped=22   rescued=0    ignored=3

**Comment by stoeps13** [comment]
```
Error from server (NotFound): nodes "cpack-server.internal.cloudapp.net"
```

Is the server name resolvable in the DNS?

**Comment by gyanenduprakash** [comment]
@arnaldovale can we have entire result for setup the k8s cluster!! ( playbooks/third_party/kubernetes/setup-kubernetes.yml)

**Comment by arnaldovale** [comment]
> ```
> Error from server (NotFound): nodes "cpack-server.internal.cloudapp.net"
> ```
> 
> Is the server name resolvable in the DNS?
Yes.
This server is not on the hosts file of the ansible controller, it´s resolved by DNS server:
![image](https://user-images.githubusercontent.com/67335382/141335774-fdbbc246-074d-4ad0-8b2b-bbe0d4619ddc.png)

**Comment by arnaldovale** [comment]
> @arnaldovale can we have entire result for setup the k8s cluster!! ( playbooks/third_party/kubernetes/setup-kubernetes.yml)

Heres the output.
[ansible_issue2.txt](https://github.com/HCL-TECH-SOFTWARE/connections-automation/files/7522139/ansible_issue2.txt)

**Comment by sabrina-yee** [comment]
> Heres the output. [ansible_issue2.txt](https://github.com/HCL-TECH-SOFTWARE/connections-automation/files/7522139/ansible_issue2.txt)

I compared your results with mine but didn't find anything usual (except it failed at `Port 10257 is in use` but it's due to the fact that it's a rerun).  
A couple more ideas to debug:
1) Run `kubectl -n kube-system get pods` to check if everything is READY 1/1
2) Check if firewall is installed and enabled (`sudo systemctl status firewalld`).  If so, temporarily disable it, run  `playbooks/hcl/cleanup/cleanup-k8s.yml --tags k8s_cleanup` then `third_party/kubernetes/setup-kubernetes.yml` again.

**Comment by arnaldovale** [comment]
> > Heres the output. [ansible_issue2.txt](https://github.com/HCL-TECH-SOFTWARE/connections-automation/files/7522139/ansible_issue2.txt)
> 
> I compared your results with mine but didn't find anything usual (except it failed at `Port 10257 is in use` but it's due to the fact that it's a rerun). A couple more ideas to debug:
> 
> 1. Run `kubectl -n kube-system get pods` to check if everything is READY 1/1
> 2. Check if firewall is installed and enabled (`sudo systemctl status firewalld`).  If so, temporarily disable it, run  `playbooks/hcl/cleanup/cleanup-k8s.yml --tags k8s_cleanup` then `third_party/kubernetes/setup-kubernetes.yml` again.

Here's the results:
![image](https://user-images.githubusercontent.com/67335382/142042145-87e5c7c3-ae88-4f4b-b8cb-125bfe6e03e2.png)

both Firewall (from ansible controller and kubernetes server) are disable and inactive
![image](https://user-images.githubusercontent.com/67335382/142042408-4be897e4-f812-44e1-a77a-d791e0358700.png)

![image](https://user-images.githubusercontent.com/67335382/142042429-70b96a68-c99d-477b-ac1a-d2bd2af3965f.png)

**Comment by ukhare** [comment]
@arnaldovale 
Looking at the first issue you posted in this thread.
It seems the vm on which you are installing K8s already had K8s which was not cleaned properly.

[kubelet.config.k8s.io kubeproxy.config.k8s.io]\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Port-6443]: Port 6443 is in use\n\t[ERROR Port-10259]: Port 10259 is in use\n\t[ERROR Port-10257]: Port 10257 is in use\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]:

Let's try from scratch, could you try following:
1. Try to force destroy K8s (if that works, else fine)
2. Force kill all services running on ports for which you are getting error "port already in use"
3. Force delete all K8s dirs and files in /etc/Kubernetes/ and ~/.kube
4. Reinstall K8s

**Comment by arnaldovale** [comment]
Hi @ukhare 
Hello,

I followed your recommendations and recreated the Azure VM for component pack.

I tried running "setup-nfs", after "setup-docker" and "setup-kubernets". I got the issue showed in the file "ansible_issue22112021". I tried again and got the issue showed on the file "ansible_issue22112021_2".

Thanks
[ansible_issue22112021.txt](https://github.com/HCL-TECH-SOFTWARE/connections-automation/files/7583621/ansible_issue22112021.txt)
[ansible_issue22112021_2.txt](https://github.com/HCL-TECH-SOFTWARE/connections-automation/files/7583622/ansible_issue22112021_2.txt)

Also I check the cpack-server for pods. It seems all pods are running:
![image](https://user-images.githubusercontent.com/67335382/142918383-33dafadf-d0c5-4915-813d-90f6d515aae4.png)

**Comment by ukhare** [comment]
@arnaldovale could you please share the output of "kubectl get nodes"
Does it give the same node name on which ansible is trying to add label ?

**Comment by stoeps13** [comment]
The task is using `{{ inventory_hostname }}`, so it is important that the hostname in inventory is the same as in DNS.
https://stackoverflow.com/questions/45908067/whats-the-difference-between-inventory-hostname-and-ansible-hostname

**Comment by arnaldovale** [comment]
Hi @ukhare. Here's the output:
![image](https://user-images.githubusercontent.com/67335382/144245204-f17a5424-1f13-42ab-91a8-0661019bf16b.png)
Yes. its with the same node name. on which ansible is trying to use. 
@stoeps13 , attached is the inventory used. The hostname is the same and we have already tested name resolution in DNS
[inventory.txt](https://github.com/HCL-TECH-SOFTWARE/connections-automation/files/7634329/inventory.txt)

Would be possible for us to have a online meeting so maybe you can review it executing?

**Comment by ukhare** [comment]
@arnaldovale did you try executing following commands manually ? If yes, pls share what is the output you are getting ?

kubectl label nodes cpack-server.internal.cloudapp.net type=infrastructure --overwrite

kubectl label nodes cpack-server type=infrastructure --overwrite

**Comment by arnaldovale** [comment]
Hi @ukhare . The first one is failing... look the outputs:
![image](https://user-images.githubusercontent.com/67335382/144426401-ea3d4dc4-ec49-4ded-8f38-378053561bd8.png)

**Comment by stoeps13** [comment]
What does `kubectl get nodes` show you?

**Comment by ukhare** [comment]
> Hi @ukhare . The first one is failing... look the outputs: ![image](https://user-images.githubusercontent.com/67335382/144426401-ea3d4dc4-ec49-4ded-8f38-378053561bd8.png)

Thats the issue. .. also as @stoeps13 also said in comment above.

your node is registered with wrong name. Please check why its not taking full name of the node or share here the output of the step when it creates node.
So we have now figured out the issue and lets try to find the cause and fix for you :)

**Comment by arnaldovale** [comment]
Guys, where it supposed to be the k8_workers_infra group? In inventory.ini there is only the k8s_masters.
And yes, this is a single K8s environment. We're following the QuickStart script.

**Comment by stoeps13** [comment]
roles/third_party/kubernetes/taint-all-nodes/tasks/main.yml

Here the  if statement starts when the group name is not available. To be honest this shows me that this mono repo approach is a big mess and not possible to understand or support.

**Comment by arnaldovale** [comment]
this is already done, take a look: 

[k8s_masters]
cpack-server.internal.cloudapp.net

[k8s_workers]
cpack-server.internal.cloudapp.net

We have the full inventory attached here: https://github.com/HCL-TECH-SOFTWARE/connections-automation/issues/152#issuecomment-983658305

**Comment by ukhare** [comment]
> roles/third_party/kubernetes/taint-all-nodes/tasks/main.yml
> 
> Here the if statement starts when the group name is not available. To be honest this shows me that this mono repo approach is a big mess and not possible to understand or support.
> 
> So https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/c9297a53dab06ea1d822952c4605419251f453f1/roles/third_party/kubernetes/taint-all-nodes/tasks/taint_workers.yml labels all k8s_workers.
> 
> So in the inventory you need to place the same server names to the groups:
> 
> * k8s_masters
> * k8s_workers

@arnaldovale Could you please share latest logs when you last time installed k8s on a completely clean VM. I was scrolling through previously shared logs but then realised that they belong to an env when k8s was not cleaned properly due to some issues.

EX: Log below said port already in use

TASK [setup-master-node : Initialize master for single node installation] ***************************************************************************************************
fatal: [cpack-server.internal.cloudapp.net]: FAILED! => {"changed": true, "cmd": ["kubeadm", "init", "--config=/tmp/k8s_ansible/kubeadm-config.yaml"], "delta": "0:00:02.196167", "end": "2021-11-11 11:33:11.905160", "msg": "non-zero return code", "rc": 1, "start": "2021-11-11 11:33:09.708993", "stderr": "W1111 11:33:11.376813   17733 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Port-6443]: Port 6443 is in use\n\t[ERROR Port-10259]: Port 10259 is in use\n\t[ERROR Port-10257]: Port 10257 is in use\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists\n\t[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists\n\t[ERROR Port-10250]: Port 10250 is in use\n\t[ERROR Port-2379]: Port 2379 is in use\n\t[ERROR Port-2380]: Port 2380 is in use\n\t[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["W1111 11:33:11.376813   17733 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]", "error execution phase preflight: [preflight] Some fatal errors occurred:", "\t[ERROR Port-6443]: Port 6443 is in use", "\t[ERROR Port-10259]: Port 10259 is in use", "\t[ERROR Port-10257]: Port 10257 is in use", "\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists", "\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists", "\t[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists", "\t[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists", "\t[ERROR Port-10250]: Port 10250 is in use", "\t[ERROR Port-2379]: Port 2379 is in use", "\t[ERROR Port-2380]: Port 2380 is in use", "\t[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "[init] Using Kubernetes version: v1.19.11\n[preflight] Running pre-flight checks", "stdout_lines": ["[init] Using Kubernetes version: v1.19.11", "[preflight] Running pre-flight checks"]}

**Comment by ukhare** [comment]
@arnaldovale 
After getting python3 console, first you need to give below command to import "os" lib

>>>Import os
>>>os.getenv('HOSTNAME')

ALSO try on you linx console below command to see what full hostname does it give

hostname -f

**Comment by arnaldovale** [comment]
Hi @ukhare 
Here's the output. Indeed, the hostname in the cpack server is being presented in the short format.
![image](https://user-images.githubusercontent.com/67335382/145587655-538ae5d7-ee75-47fd-903a-3224128ddaf1.png)
![image](https://user-images.githubusercontent.com/67335382/145587745-40e431e0-4bf3-4ca4-88e0-823b168c2ed4.png)

![image](https://user-images.githubusercontent.com/67335382/145587793-5d538091-848a-4001-aa45-4af7d6bb15e9.png)

And here's the host file for the ansible machine:
![image](https://user-images.githubusercontent.com/67335382/145587912-edc55ccb-063a-4729-b3f5-4eb59f120ebe.png)

**Comment by stoeps13** [comment]
Move the short hostname to the end of the line in /etc/hosts

**Comment by arnaldovale** [comment]
It's done. Should we try to run the script again as is?
![image](https://user-images.githubusercontent.com/67335382/145631024-d583c285-d771-4acc-95b0-9262ad88925f.png)

**Comment by ukhare** [comment]
> It's done. Should we try to run the script again as is? ![image](https://user-images.githubusercontent.com/67335382/145631024-d583c285-d771-4acc-95b0-9262ad88925f.png)

@arnaldovale 

Yes, that was the issue behind not being able to find the node with full hostname.
it's done. Now you should clean everything and execute ansible from scratch.

**Comment by ukhare** [comment]
@arnaldovale please close this issue if you have bypassed the error you were getting at this step.

**Comment by arnaldovale** [comment]
@ukhare , the team has executed the cleanup script. Please, take a look at the result:
[ansible_result.txt](https://github.com/HCL-TECH-SOFTWARE/connections-automation/files/7756033/ansible_result.txt)

**Comment by ukhare** [comment]
@arnaldovale looks good to me.
I also see in attached logs that your team has successfully created Kubernetes cluster and setup helm using Ansible.

Please feel free to close this issue as the existing issue has been resolved in your environment.

If there is any new issue, i would request you to create a separate issue to avoid any kind of confusion.

**Comment by arnaldovale** [comment]
Closing this issue. Thanks team! @ukhare @stoeps13 @sabrina-yee @gyanenduprakash
