### ISSUE TITLE
Connections 6.5 CR1 install

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#153]
Hi,

I had to install a Connections 6.5 environment for iFix testing.

I found that the installation installs a plain 6.5, there is no option to add the CR1 as additional repository to the installation manager or something like this. The playbook just ignores the fix. So even when I enable ifix install and provide the latest ifix from Flexnet, I get the message that the version don't match (clear because the ifix needs to be deployed on top of CR1).

Anybody interested in 6.5CR1 (mainly for testing)? Or do you already have something prepared to install the CR1 which I have overlooked?

The howtos mention a example here: https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/97337e160df324509bbb1398ef83d15e72f59bb4/documentation/howtos/connections_upgrade.md?plain=1#L17 but it is not available in the repository master any more. So it would be cool to have a working example howto deploy 6.5CR1 or 6.5.0.1 like it is named in the howto.

Btw the fix itself says his name / version is 6.5.0.0_CR1 and this is also written to logs and version files. So the 6.5.0.1 strings should be replaced.

![image](https://user-images.githubusercontent.com/1975258/139418552-fd35fadb-fce3-4f38-8729-76bb95ba1ba9.png)

Thanks for any hints.
Regards
Christoph

**Comment by stoeps13** [comment]
I think that cnx_fixes_files and the default variable are missing in the examples, will add today and try again.

https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/ec8844f6b0002f1e23799facfc36427d11395089/roles/hcl/connections/vars/main.yml#L72

**Comment by sabrina-yee** [comment]
@stoeps13 - we're gathering more info from internal team and will make adjustment accordingly.

**Comment by stoeps13** [comment]
Created PR with description about howtos and issues https://github.com/HCL-TECH-SOFTWARE/connections-automation/pull/159#issue-771585916
