### ISSUE TITLE
selfregistration-config.xml not valid xml in 6.5

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#158]
The Fix for 6.5CR1 can't be deployed, because Installation Manager logs a non-valid xml file: selfregistration-config.xml

In 6.5 the selfregistration-config.xsd does not know about invite-user-type which is set here:

https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/97337e160df324509bbb1398ef83d15e72f59bb4/roles/hcl/connections/post_install_config/tasks/setup_invite_config.yml#L27-L31

So to have valid xml and to be able to install the latest fixes this needs to be removed for the 6.5 installation!

This needs to be changed to:
```
- name:                                     Set Invite user type
  xml:
    path:                                   "{{ __selfreg_full_path }}"
    xpath:                                  "{{ __selfreg_invite_usertype_xpath }}"
    value:                                  "{{ invite_user_type | default('internal') }}"
  when:
    - __cnx_major_version == '7'
```

**Comment by sabrina-yee** [comment]
Hi @stoeps13, I just checked a 6.5 CR1 deployment and confirmed `selfregistration-config.xml` is there.  Could you please check the version in `/opt/HCL/Connections/version.txt` that it's 6.5 CR1?   Thanks.

**Comment by stoeps13** [comment]
Hi @sabrina-yee 
can you deploy 6.5.0.0 and xmllint selfregistration-config.xml please? There is an element invite-user-type which is not valid! Have you installed with the actual repo?
When I deploy 6.5.0.0 and the run Installation Manager to update to 6.5CR1 it fails, because the installer can't valideate selfregistration-config.xml.

**Comment by sabrina-yee** [comment]
We do not support installing 6.5.0.0.  Having said that, do you have `cnx_enable_invite` in your inventory?  I believe the default is false so it shouldn't run that step.

**Comment by stoeps13** [comment]
Even when you install 6.5CR1 this step will break the xmllint.
Can you please check you selfregistration-config.xml and see if invite-user-type is set? If yes, please run:
`xmllint -noout -schema selfregistration-config.xsd selfregistration-config.xml`

I need to test invite with the latest CFix, so why should I remove the variable? What I want to say is, that the connections post tasks create a xml element which can't be handled from the 6.5 invite (or is invalid for this xsd). 

Btw I already asked how I can deploy 6.5CR1 in one step, but the repository install 6.5.0.0 and then updates, but the documented steps in the documentation part point to environment examples which are not available in the repo anymore. So when I interpret the playbook, the installlation steps are:

1. connections 6.5
2. post config
3. 6.5 CR1
4. CFix 2109

As 6.5CR1 validates the xml during update, this will fail. (in the moment I do step 3 manually)

**Comment by sabrina-yee** [comment]
I see your point, will check with development when we added `invite-user-type` and adjust the `when` accordingly.
The 6.5 example inventory is in https://github.com/HCL-TECH-SOFTWARE/connections-automation/tree/main/environments/examples/cnx6/db2.  The path in documentation will be updated in the next release.

As for deploying 6.5 CR1 in one step, I believe there is a Connections install kit for CR1 that, if install on a clean system, will install it from scratch all the way up to CR1.  I can get obtain a FlexNet link if you need that info.

**Comment by stoeps13** [comment]
Afaik CR1 needs to be added as second repository during deployment of Connections 6.5, I don't think you can just use the CR1 to deploy directly, but will try tomorrow. 
The example group_vars file you mention uses the default 6.5 package.

**Comment by stoeps13** [comment]
> I see your point, will check with development when we added `invite-user-type` and adjust the `when` accordingly. The 6.5 example inventory is in https://github.com/HCL-TECH-SOFTWARE/connections-automation/tree/main/environments/examples/cnx6/db2. The path in documentation will be updated in the next release.
> 
> As for deploying 6.5 CR1 in one step, I believe there is a Connections install kit for CR1 that, if install on a clean system, will install it from scratch all the way up to CR1. I can get obtain a FlexNet link if you need that info.

See https://github.com/HCL-TECH-SOFTWARE/connections-automation/issues/153#issuecomment-957112110 the used cnx_fixes_files is missing in all examples.

**Comment by stoeps13** [comment]
For your information @sabrina-yee: I have updated the environment to 6.5CR1 and latest CFix! When I add invite-user-type to selfregistration-config.xml it is still invalid, the xsd doesn't know of this attribute.

**Comment by stoeps13** [comment]
Created PR https://github.com/HCL-TECH-SOFTWARE/connections-automation/pull/159#issue-771585916 will close this and move further dicussions in the PR.
