### ISSUE TITLE
SDI Fixpack not installed

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#16]
SDI Fixpack is listed in the needed software package list, but it is nowhere deployed.

**Comment by dejo1307** [comment]
Good point. Let me check if our package is actually already patched (hence FP not installed after it) or not. I don't remember anymore what was exactly the case when we added this part of automation.

**Comment by dejo1307** [comment]
And another thing I need to check (a note to myself) are exact support version matrices for CNX and SDI.

**Comment by dejo1307** [comment]
I'm pulling this into the current sprint today, started working on it yesterday. My ETA is end of this week, worst case beginning of the next with all the testings.

**Comment by dejo1307** [comment]
This will be merged as a part of https://github.com/HCL-TECH-SOFTWARE/connections-automation/pull/32
