### ISSUE TITLE
updateInstaller extraction creates subfolders

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#165]
Hi,
I installed 7.0 with latest CFix 2110 today and when I check the updateInstaller folder (tried to check the log) I see this:

```
[root@cnx7-was updateInstaller]# pwd
/opt/HCL/Connections/updateInstaller
[root@cnx7-was updateInstaller]# tree -L 5
.
├── fixes
│   └── CFix.70.2110-IC7.0.0.0-Common-Fix.jar
└── HCL_Connections_Install
    └── tools
        └── updateInstaller
            ├── bin
            │   ├── wpwsadmin.bat
            │   └── wpwsadmin.sh
            ├── config
            │   ├── earFullExpander.py
            │   ├── exportAppEAR.py
            │   ├── updateAppEAR.py
            │   └── updateApp.py
            ├── earLauncher
            │   └── launcher.exe
            ├── fixes
            ├── jvm
            │   └── aix
            ├── lib
            │   ├── commons-collections-3.2.1.jar
            │   ├── commons-configuration-1.5-plus-node-clone.jar
            │   ├── commons-lang-2.4.jar
            │   ├── commons-logging-1.0.4.jar
            │   ├── icu4j-68.1.jar
            │   ├── lcui.jar
            │   ├── nativefile.jar
            │   ├── org.eclipse.core.commands.jar
            │   ├── org.eclipse.equinox.common.jar
            │   ├── org.eclipse.jface.jar
            │   ├── org.eclipse.swt.gtk.aix.ppc64.jar
            │   ├── org.eclipse.swt.gtk.linux.s390x_3.7.0.v3735b.jar
            │   ├── org.eclipse.swt.gtk.linux.x86_64.jar
            │   ├── org.eclipse.swt.win32.win32.x86_64.jar
            │   └── org.eclipse.ui.forms_3.5.100.v20110425.jar
            ├── updateSilent.bat
            ├── updateSilent.sh
            ├── updateWizard.bat
            ├── updateWizard.sh
            └── version
                └── lcui.product
                
```

so HCL_Connections_Install/tools/updateInstaller are too much.

I checked the packages HCL_Connections_79_updateInstaller_2104.zip and 2102.zip, both show this folder structure! Should start with updateInstaller, then we can just decompress in /opt/HCL/Connections.

**Comment by stoeps13** [comment]
I see in the repo that the updateSilent.sh is called from this path, but it seems weird! The log and /opt/HCL/Connections/version/log tell me the update is installed, but the updateWizard.sh can't uninstall it, it seems it can't find it. So I think it will be a problem with the next update.

**Comment by sabrina-yee** [comment]
Thanks for the feedback.  The current approach expects the updateInstaller zip and fix jar are separate (https://github.com/HCL-TECH-SOFTWARE/connections-automation#installing-ifix-for-hcl-connections) but as you point they are bundled as one zip.  We'll create an internal ticket to update.

**Comment by stoeps13** [comment]
Not sure which update HCL_Connections_70_Update.jar is, but the newest CFix update name is:
CFix.70.2110-IC7.0.0.0-Common-Fix.jar

I tried with all commands, but the updateInstaller does not know that this fix is installed.

**Comment by stoeps13** [comment]
The Connections documentation says extract to temp folder and move the files: https://help.hcltechsw.com/connections/v7/admin/migrate/t_im_upgrade.html

**Comment by sabrina-yee** [comment]
ok, have you tried these settings?
ifix_apar:                                     CFix.70.2110
ifix_file:                                       CFix.70.2110-IC7.0.0.0-Common-Fix.jar   (this jar would need to be in the same dir as `cnx_repository_url`)
cnx_ifix_installer:                        "updateInstaller_2110.zip"         (or whatever the updateInstaller zip is called)

**Comment by stoeps13** [comment]
Yes, the installation works, I can see the log files in /opt/HCL/Connections/version/log but when I try to check the installed fixes with updateWizard or updateSilent, or try to uninstall it, the update*.sh tells me that no fix is installed. I think that's related to the wrong folder.

**Comment by sabrina-yee** [comment]
> Installation was successful, I just wondered why I can't see the fix in updateWizard as installed.
> 
trying it myself...

**Comment by sabrina-yee** [comment]
I can reproduce the issue where using the updateWizard it reports there is no fix installed.  It's out of scope of this project but I'll report it to the team.  

As you stated it's a directory issue, I moved `/opt/HCL/Connections/updateInstaller/HCL_Connections_Install/tools/updateInstaller` to `/opt/HCL/Connections/updateInstaller2`, running updateWizard from there detects the cfix.

![image](https://user-images.githubusercontent.com/75322195/140418176-f3175fcb-fe0f-423f-8b7e-606e24523bd9.png)

**Comment by stoeps13** [comment]
So it could be fixed when the updateInstaller is moved to the documented position. I think following the documentation makes sense here.

**Comment by sabrina-yee** [comment]
We'll address in later release.

**Comment by sabrina-yee** [comment]
Addressed in Jan release.
