### ISSUE TITLE
DB2 package name variable not working

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#208]
Hi,
the variables documentation says that the db2 package name can be set with `db2_package_name:` 
https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/d8c5d807be391ef0703ebe5d704dbc79d5f01c5d/documentation/VARIABLES.md?plain=1#L70

But the variables in the db2 installation role, just decide dependent on the variable `install_latest_db2`
https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/8521ea7754c4cadf83e6e1111ab2069331414be0/roles/third_party/ibm/db2-install/vars/main.yml#L5

As there are known vulnerabilities with the 11.5.6 packages https://support.hcltechsw.com/csm?id=kb_article&sysparm_article=KB0099179, this should be updated and the documented variable should be used.
Regards
Christoph

**Comment by nitinjagjivan** [comment]
Hi @stoeps13,

If user specifies a value for db2_package_name in the inventory then that value will be assigned to the ['__package_name'](https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/8521ea7754c4cadf83e6e1111ab2069331414be0/roles/third_party/ibm/db2-install/vars/main.yml#L14).

The scenario which you described in the above issue is applicable only when user doesn't set 'db2_package_name' in the inventory.

**Comment by stoeps13** [comment]
Hi,

Would you mind to point me to the definition, where this should happen?

Regards
Christoph

**Comment by nitinjagjivan** [comment]
There is a link in my comment. Let me add it here-
https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/8521ea7754c4cadf83e6e1111ab2069331414be0/roles/third_party/ibm/db2-install/vars/main.yml#L14

**Comment by stoeps13** [comment]
Sorry @nitinjagjivan I looked into the wrong line. You're right it grabs from db2_package_name
