### ISSUE TITLE
Upgrade TDI to Java8

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#212]
I tried to update TDI to Java 8, but the used package default name can't be found anywhere.

https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/64b6dd9c6e5589cae05fb61b7dca715ecd09b779/roles/third_party/ibm/tdi-install/vars/main.yml#L12

I checked IBM and Flexnet for this file, but I can't find it. Any hint where I can find this package?

Thanks 
Christoph

**Comment by sabrina-yee** [comment]
It's on FlexNet named `Service Refresh 6 Fix Pack 25 for IBM Java Runtime Technology version 8.0 - Linux` in the `HCL_Connections_7.0` list.  I see a newer version is used there `ibm-java-jre-8.0-6.25-linux-x86_64.tgz` so please override the var.  We'll adjust in the next push.

**Comment by stoeps13** [comment]
Thanks @sabrina-yee, found the package in Connections 7.0 Folder, I searched in 7.0-Upates.
