### ISSUE TITLE
mongodb5 image not available

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#224]
Hi,
got this link from support https://opensource.hcltechsw.com/connections-doc/admin/install/installing_mongodb_5_for_component_pack_8.html?h=mongo after I mentioned that the image is not available on Harbor.
The steps are not built in the roles/playbooks. And the repository to build the container is not available at GitHub too.
Regards
Christoph

**Comment by stoeps13** [comment]
Yes, but I see no role or task to build the image. Is this a manual task?

**Comment by sabrina-yee** [comment]
yes, building MongoDB is a manual task.

**Comment by stoeps13** [comment]
Can you explain the reason why this is not automated?

Then the infrastructure helm chart should get a wait message and not just fail.
