### ISSUE TITLE
Check if master is already initialized

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#228]
The check greps for 'master', but installed Kubernetes 1.24 shows just control-plane, so this check fails, even when the master is already initialized.

https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/4871474b92333cefdaadfb1a3e48263f216d54a6/roles/third_party/kubernetes/setup-master-node/tasks/init_master_latest.yml#L2

**Comment by sabrina-yee** [comment]
Just submitted a fix.
