### ISSUE TITLE
Default containerd version 1.4.x is quite old

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#229]
The default containerd version is about 2 years old. Kubernetes 1.24.1 is tested with 1.6.4, this should be updated.

Regards
Christoph

**Comment by sabrina-yee** [comment]
Duly noted, we're working on upgrade it.

**Comment by stoeps13** [comment]
Just as an update. Kubernetes 1.24 needs at least 1.5.11 or 1.6.4. 
https://containerd.io/releases/#kubernetes-support

The used 1.4 is out of life since March 2022.

**Comment by stoeps13** [comment]
Latest update

**Comment by stoeps13** [comment]
1.6.9 is used now after the latest update
