### ISSUE TITLE
mongodb5 role breaks infrastructure helm chart deployment

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#231]
Yes, but I see no role or task to build the image. Is this a manual task?

_Originally posted by @stoeps13 in https://github.com/HCL-TECH-SOFTWARE/connections-automation/issues/224#issuecomment-1315831888_
      
Why is there no role to build the image? Until the image is available, the infrastructure helm chart deployment fails, because it waits that mongo5 is available.

**Comment by sabrina-yee** [comment]
We have a separate process internally so building Mongo is not part of our deployment automation (i.e. this repo).  Having said that, you're right that until the image is available, the infrastructure helm chart deployment will fail so updated the documentation to clarify that.  Thanks.

**Comment by stoeps13** [comment]
The documentation says this project is the recommended way to install Connections, your answer sound like it is a side project of the internal development environments. 

I will work on a role to build the image,  inserting a manual step in the middle of the deployment is against everything I know on IAC and Devops.
