### ISSUE TITLE
Kubernetes versions just with .1 are available

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#238]
Kubernetes has released 1.24.8, but the playbook seems to just install 1.24.1 (same for other versions, just x.y.1 templates are available. Installation fails if you set kubernetes_version to something different than x.y.1, no kubeadm config template for higher versions are available.
From security perspective, newer versions should be possible and should be used as default. https://v1-24.docs.kubernetes.io/releases/download/

**Comment by sabrina-yee** [comment]
Agreed, we're working on K8s 1.25 support and will test with latest.

**Comment by stoeps13** [comment]
So, you're changing the helm charts?
I've seen several deprecated messages in 1.24, for stuff which was removed in 1.25.

**Comment by sabrina-yee** [comment]
Yes, working on changing the Helm charts that don't work on K8s 1.25 anymore.

**Comment by stoeps13** [comment]
Hi @sabrina-yee,
just deploying the last updates and trying the Kubernetes 1.25 update. First thing I felt over is the default version 1.25.1 why not using 1.25.6, there are tons of known issues with the .1 version.
Regards,
Christoph

**Comment by sabrina-yee** [comment]
Noted, you can override the default by setting `__kubernetes_version`.
https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/3d6f96b5dd37112ebc28a881217fa5bdcba64735/roles/third_party/kubernetes/kubernetes-install/vars/main.yml#L2

We'll bump the default in our next push.

**Comment by stoeps13** [comment]
Setting the version to 1.25.6 fails because the Jinja template is just for 1.25.1

**Comment by sabrina-yee** [comment]
There was an improvement made to move away from the dependency of version specific template.

**Comment by stoeps13** [comment]
With the latest

**Comment by stoeps13** [comment]
With the latest update, the update / install of K8s falls back to a generic kubeadm file.
