### ISSUE TITLE
Update WAS install for FP22

### ISSUE THREAD

**Issue by wannesrams** [HCL-TECH-SOFTWARE/connections-automation#241]
Can the following file please be updated for WAS FP22
roles/third_party/ibm/wasnd/was-nd-fix-install/vars/main.yml

I tested with this and works fine
__was_fp_version_fp22:     "8.5.5022.20220703_1123"
__was_fp_files_fp22:
  - { file_name: 8.5.5-WS-WAS-FP022-part1.zip }
  - { file_name: 8.5.5-WS-WAS-FP022-part2.zip }
  - { file_name: 8.5.5-WS-WAS-FP022-part3.zip }

and 
__was_fp_version_latest:   "{{ was_fp_version_latest | default( __was_fp_version_fp22 ) }}"
__was_fp_files_latest:     "{{ was_fp_files_latest | default( __was_fp_files_fp22 ) }}"

/roles/third_party/ibm/ihs/ibm-http-server-fix-install/vars/main.yml

__ihs_fp_version_latest:  "{{ ihs_fp_version_latest | default( __ihs_fp_version_fp22 ) }}"
__ihs_fp_files_latest:    "{{ ihs_fp_files_latest | default( __ihs_fp_files_fp22 ) }}"

__ihs_fp_version_fp22:    "8.5.5022.20220703_1123"
__ihs_fp_files_fp22:
  - { file_name: 8.5.5-WS-WASSupplements-FP022-part1.zip }
  - { file_name: 8.5.5-WS-WASSupplements-FP022-part2.zip }
  - { file_name: 8.5.5-WS-WASSupplements-FP022-part3.zip }

__wct_fp_version_latest:  "{{ wct_fp_version_latest | default( __wct_fp_version_fp22 ) }}"
__wct_fp_files_latest:    "{{ wct_fp_files_latest | default( __wct_fp_files_fp22 ) }}"

__wct_fp_version_fp22:    "8.5.5022.20220703_1123"
__wct_fp_files_fp22:
  - { file_name: 8.5.5-WS-WCT-FP022-part1.zip }
  - { file_name: 8.5.5-WS-WCT-FP022-part2.zip }

**Comment by sabrina-yee** [comment]
@wannesrams certainly, we're working on a release which includes WAS FP22 changes.

**Comment by wannesrams** [comment]
There also seems to be an issue with the TLS 1.3 ciphers not being compatible with the IBM Http server ones. Or a bug in FP22 where it does not fallback to 1.2. As a workaround I set the TLS to 1.2 only

**Comment by sabrina-yee** [comment]
Latest repo release includes the steps to install FP22 and [PH49497](https://www.ibm.com/support/pages/apar/PH49497).
