### ISSUE TITLE
failed to fetch https://hclcr.io/chartrepo/cnx/index.yaml : 403 Forbidden

### ISSUE THREAD

**Issue by canklamassono** [HCL-TECH-SOFTWARE/connections-automation#244]
Hello, i have already succesfully installed Connections 8 via your amazing scripts but I am having trouble with the Component Pack:

The Task:
TASK [component-pack-harbor : Add Helm repository https://hclcr.io/chartrepo/cnx] does not complete.

Manually trying gives me:
Error: looks like "https://hclcr.io/chartrepo/cnx" is not a valid chart repository or cannot be reached: failed to fetch https://hclcr.io/chartrepo/cnx/index.yaml : 403 Forbidden

I have logged in with my HCL Software account and am Onboarded via OIDC provider.
I copied the CLI Secret and used it as:
helm repo add v-connections-helm https://hclcr.io/chartrepo/cnx --username <MYUSERNAME> --password <MYCLISECRET> --pass-credentials

I can see the following repos, but apparently cnx and chartrepo seems to be missing.
![harbor](https://user-images.githubusercontent.com/122796642/212687806-575c85c1-fcaa-4208-aa1d-dc20bee337c9.png)

What should i do now? Do i use a wrong accout? I have downloaded all the files for the installation beforehand at Flexnet with that account.

**Comment by sabrina-yee** [comment]
Hi @canklamassono looks like some sort of a Harbor entitlement issue.  Please open a ticket with our Support team to assist.  Thanks!

**Comment by canklamassono** [comment]
The Support-Team has resolved my request. Thank you.
