### ISSUE TITLE
documentation wrong

### ISSUE THREAD

**Issue by MagnaFrisia90** [HCL-TECH-SOFTWARE/connections-automation#245]
Based on initial description for "Quick start for setting up HCL Connections and Component Pack using Ansible automation" there should exist a host called "ansible". But all controller-related actions written under this topic are executed on the "web"-node which should be the webproxy but not the controller host with ansible.

**Comment by sabrina-yee** [comment]
Thanks, we'll update it as part of the release for 8.0 CR1 soon.

**Comment by sabrina-yee** [comment]
Quick start has been updated to use the ansible controller node.
