### ISSUE TITLE
FAQ links not working

### ISSUE THREAD

**Issue by MagnaFrisia90** [HCL-TECH-SOFTWARE/connections-automation#255]
The links under https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/main/documentation/FAQ.md that should jump to the chapters a few lines beneath do not work - they lead to "404"

**Comment by nitinjagjivan** [comment]
Thanks @MagnaFrisia90. It is fixed now. PR - https://github.com/HCL-TECH-SOFTWARE/connections-automation/pull/257
