### ISSUE TITLE
helm repo add v-connections-helm - "no valid repository"

### ISSUE THREAD

**Issue by MagnaFrisia90** [HCL-TECH-SOFTWARE/connections-automation#267]
Hi,

not sure if this is even part auf "connections-automation" but I can not add the helm-repo for connections.
I want to use my HCL ID credentials, which work if I manually click on "OIDC login".
https://opensource.hcltechsw.com/connections-doc/v8-cr1/admin/install/cp_install_services_tasks.html#section_ln3_qp3_dvb

> [root@solcon15 pv-connections]# helm repo add v-connections-helm https://hclcr.io/chartrepo/cnx --username jhs@solvito.de --password 123456 --pass-credentials
> Error: looks like "https://hclcr.io/chartrepo/cnx" is not a valid chart repository or cannot be reached: failed to fetch https://hclcr.io/chartrepo/cnx/index.yaml : 401 Unauthorized

Did anybody manage to add the helm repo with its HCL ID credentials ? 
"https://hclcr.io/chartrepo/cnx" is error 404 | https://hclcr.io/harbor only works with OIDC.

And if this is not a "connections-automation"-topic => classic hcl support case ?

Thanks in advance !

**Comment by umeli** [comment]
Did you use the cli secret from your userprofile ?
![image](https://user-images.githubusercontent.com/710539/221177442-b6febd2f-0b24-4e29-87d0-293581a183d8.png)

**Comment by MagnaFrisia90** [comment]
I have tried native HCL ID password & CLI secret

**Comment by MagnaFrisia90** [comment]
I have tried native HCL ID password but not CLI secret.
CLI secret is working ;-)
