### ISSUE TITLE
Cert copy from wrong host

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#281]
The component pack install playbook runs against component_pack_master. https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/6284e97dc630da1d84ba873d066be366655e8694/playbooks/hcl/harbor/setup-component-pack-only.yml#L8

but the metrics enable role copies from k8s_master[0], 
https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/6284e97dc630da1d84ba873d066be366655e8694/roles/hcl/component-pack-harbor/tasks/enable_es_metrics.yml#L231

So, when you install from a different machine than the k8s_master, then the copy fails. Replacing with component_pack_master instead of k8s_master makes the role more portable.

**Comment by nitinjagjivan** [comment]
Thank you @stoeps13. #282 merged.
