### ISSUE TITLE
db2_wizards variables not used

### ISSUE THREAD

**Issue by marde16** [HCL-TECH-SOFTWARE/connections-automation#285]
The role connections-wizards contains not used variables.
https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/4e0466a74b400835172d5a83c70ffcbac7e62c4f/roles/hcl/connections-wizards/vars/main.yml#L2-L3

The variable "db2_wizards_download_locaiton" has a typo and isn't used in the connections wizard role.

The variable "db2_wizards_package_name" isn't used, too.

I got the following output when I grep for these variables:

>  grep -R "db2_wizards_download_locaiton"
> roles/hcl/connections-wizards/vars/main.yml:db2_wizards_download_locaiton:  "{{ connections_wizards_download_location }}"

>  grep -R "db2_wizards_package_name"   
> roles/hcl/connections-wizards/vars/main.yml:db2_wizards_package_name:       "{{ connections_wizards_package_name }}"

**Comment by sabrina-yee** [comment]
Thanks, will remove in next push.

**Comment by marde16** [comment]
Fixed in July 2023 cnx8 CR3 release (#304)
