### ISSUE TITLE
Missing LDAP connection check in TDIsol_install

### ISSUE THREAD

**Issue by marde16** [HCL-TECH-SOFTWARE/connections-automation#291]
The TDIsol installation hangs at task `Run collect_dns.sh` when the LDAP port isn't reachable.

**Comment by sabrina-yee** [comment]
It appears that the hang is from the collect_dns.sh` script itself as I can reproduce this issue manually with an invalid LDAP host.  Please contact HCL Connections Support to address the issue.  Thanks.
