### ISSUE TITLE
IHS httpd.conf duplicate rewrites

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#295]
These two blocks make both the same, forward to HTTPS and forward host to /homepage. I would recommend to just keep the second block.

https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/c1856b66ea96c24b10c54ff45c53da76b84721b3/roles/third_party/ibm/ihs/ibm-http-httpdconf/templates/httpd.conf.j2#L1080-L1086

https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/c1856b66ea96c24b10c54ff45c53da76b84721b3/roles/third_party/ibm/ihs/ibm-http-httpdconf/templates/httpd.conf.j2#L1119-L1128

**Comment by stoeps13** [comment]
Hi @sabrina-yee,

still annoying to remove each time after deploying something with the Ansible roles.

Any comment from Dev? 

I prefer the block within `<IfModule mod_rewrite.c>` because it does not break the http, when the rewrite role is not available.

Regards,
C

**Comment by sabrina-yee** [comment]
Apologies for the delay. I just sent a follow up to the Dev team on this and will circle back soon.

**Comment by sabrina-yee** [comment]
@stoeps13 duplicate block has been removed, thanks.
