### ISSUE TITLE
Insecure tiny editors application.conf

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#320]
The template for the tiny editors application.conf is generated with the following template:
https://github.com/HCL-TECH-SOFTWARE/connections-automation/blame/main/roles/third_party/tiny-editors-install/templates/configure-tiny-editors.j2

```
ephox {
allowed-origins {
origins = [

"http://{{ dmgr_hostname }}",
"https://{{ dmgr_hostname }}",
"http://{{ dmgr_hostname }}:9081",
"https://{{ dmgr_hostname }}:9444"

]
}
http {
websphere.use-ssl-config = false
trust-all-cert = true
}
}
```

Allowed origin is for CORS requests, so when you want to use the spellchecking service, these origins need to contain the values from IHS / nginx, but not DMGR (the dmgr does not hurt, but is useless)! So this needs to be replaced with:

```
cnx_component_pack_ingress
cnx_application_ingress
```
and the IHS_servers hostnames.

Then disabling the Websphere SSL config and trust all certs is just unsecure (documentation for example says this allows MITM attacks). So when the `http` part is removed, then Tiny reads the CellDefaultTruststore and this ssl store contains all needed certificates to trust even self signed certificates.

Documentation for application.conf: https://help.hcltechsw.com/connections/v7/admin/install/tiny_editors/r_application-conf.html

**Comment by pln-git4011** [comment]
Hi Christoph, well-made points about the configuration settings in the application.conf file. An internal task to update the file has been created and it will be updated near future.
