### ISSUE TITLE
Disable server version in nginx

### ISSUE THREAD

**Issue by marde16** [HCL-TECH-SOFTWARE/connections-automation#330]
The version of the nginx server is not disabled by the playbook.

I see the nginx version `nginx/1.24.0` in the web browser console.

Please add `server_tokens off;` in the customizer template.

https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/9eb050fdad217266a0fed3e2e35ebaf9f0b20d62/roles/third_party/nginx-install/templates/customizer.conf.j2#L15-L26

**Comment by sabrina-yee** [comment]
`server_tokens off` was added as part of the CR6 release.
